node {
    def mvnHome
    stage('Preparation') { // for display purposes
       echo 'setp 1....'
    }
    stage('Build') {
        echo 'setp 2222....'
    }
    stage('Results') {
        echo 'setp 3....'
    }
}