//定义项目地址
def project_url = 'https://gitee.com/lingwh1995/springcloud-eureka.git'
node {
    def mvnHome
    /*指定在那台Jenkins节点上运行*/
    agent { label '192.168.0.5'}
    /*从远程仓库检出代码*/
    stage('从远程仓库检出代码') {
        echo '开始从远程仓库检出代码...'
        checkout([
            $class: 'GitSCM',
            branches: [[name: '*/master']], extensions: [],
            userRemoteConfigs: [[url: "${project_url}"]]
        ])
        echo '完成从远程仓库检出代码...'
    }

    /**
     * maven命令扩展:实现多模块情况下只针对某一个模块打包
     * -pl, --projects
     *      Build specified reactor projects instead of all projects
     *      指定项目其中的一个模块及其依赖
     *  -am, --also-make
     *      If project list is specified, also build projects required by the list
     *      自动构建该模块所依赖的其他模块
     *
     */
    stage('打包->安装->构建镜像->推送到私服') {
        echo '开始 打包->安装->构建镜像->推送到私服...'
        sh "mvn clean install  -DskipTests -pl springcloud-basic-sample-register-center-single-node7005 -am"
        sh "mvn clean install  -DskipTests -pl springcloud-basic-sample-provider-cluster-node-payment8009 -am"
        sh "mvn clean install  -DskipTests -pl springcloud-basic-sample-provider-cluster-node-payment8010 -am"
        sh "mvn clean install  -DskipTests -pl springcloud-basic-sample-consumer-loadbalance-openfeign-dynamic-servicename-order80 -am"
        echo '结束 打包->安装->构建镜像->推送到私服...'
    }

    stage('删除docker中本地镜像') {
        echo '开始删除docker中本地镜像....'
        echo '完成删除docker中本地镜像....'
    }
}