//定义项目地址
def project_url = 'https://gitee.com/lingwh1995/springcloud-eureka.git'
node {
    def mvnHome
    /*指定在那台Jenkins节点上运行*/
    agent { label '192.168.0.5'}
    /*从远程仓库检出代码*/
    stage('从远程仓库检出代码') {
        echo '开始从远程仓库检出代码...'
        checkout([
            $class: 'GitSCM',
            branches: [[name: '*/master']], extensions: [],
            userRemoteConfigs: [[url: "${project_url}"]]
        ])
        echo '完成从远程仓库检出代码...'
    }

    stage('安装并推送到私服') {
        echo '开始安装并推送到私服...'
        sh "mvn springcloud-api-commons clean install"
        sh "mvn springcloud-basic-sample-register-center-single-node7005 clean install"
        sh "mvn springcloud-basic-sample-provider-cluster-node-payment8010 clean install"
        sh "mvn springcloud-basic-sample-provider-cluster-node-payment8009 clean install"
        sh "mvn springcloud-basic-sample-consumer-loadbalance-openfeign-dynamic-servicename-order80 clean install"
        echo '结束安装并推送到私服...'
    }
    stage('Results') {
        echo 'setp 3....'
    }
}