//定义项目地址
def project_url = 'https://gitee.com/lingwh1995/springcloud-eureka.git'
//定义deploy.sh的位置
def remote_shell_path = '/devops-script/deploy.sh'
//定义deploy.sh的使用的docker-compose.yml文件的名称，不同的项目这个文件的名称是不同的
def docker_compose_yml_name = 'docker-compose-springcloud-eureka.yml'

node {
    echo '开始执行自动化...'
    /*指定在那台Jenkins节点上运行*/
    agent { label '192.168.0.5'}

    /*从远程仓库检出代码*/
    stage('从远程仓库检出代码') {
        echo '开始 从远程仓库检出代码...'
        checkout([
            $class: 'GitSCM',
            branches: [[name: '*/master']], extensions: [],
            userRemoteConfigs: [[url: "${project_url}"]]
        ])
        echo '完成 从远程仓库检出代码...'
    }

    /**
     * maven命令扩展:实现多模块情况下只针对某一个模块打包
     * -pl, --projects
     *      Build specified reactor projects instead of all projects
     *      指定项目其中的一个模块及其依赖
     *  -am, --also-make
     *      If project list is specified, also build projects required by the list
     *      自动构建该模块所依赖的其他模块
     *
     */
    stage('打包->安装->构建镜像->推送到私服->删除docker中本地镜像') {
        echo '开始 打包->安装->构建镜像->推送到私服->删除docker中本地镜像...'
        sh "mvn clean install  -DskipTests -pl springcloud-basic-sample-register-center-single-node7005 -am"
        sh "mvn clean install  -DskipTests -pl springcloud-basic-sample-provider-cluster-node-payment8009 -am"
        sh "mvn clean install  -DskipTests -pl springcloud-basic-sample-provider-cluster-node-payment8010 -am"
        sh "mvn clean install  -DskipTests -pl springcloud-basic-sample-consumer-loadbalance-openfeign-dynamic-servicename-order80 -am"
        echo '完成 打包->安装->构建镜像->推送到私服->删除docker中本地镜像...'
    }

    /**
     *安装Publish Over SSH插件，使用插件的功能触发远程的shell脚本的执行
     */
    stage('自动部署上传到私服中的所有镜像到docker') {
        echo '开始 自动部署上传到私服中的所有镜像到docker...'
        sshPublisher(
            publishers:
                [
                    sshPublisherDesc(
                        configName: '192.168.0.4',
                        transfers: [
                            sshTransfer(
                                cleanRemote: false,
                                excludes: '',
                                execCommand: '${remote_shell_path} ${docker_compose_yml_name}',
                                execTimeout: 120000,
                                flatten: false,
                                makeEmptyDirs: false,
                                noDefaultExcludes: false,
                                patternSeparator: '[, ]+',
                                remoteDirectory: '',
                                remoteDirectorySDF: false,
                                removePrefix: '',
                                sourceFiles: ''
                            )
                        ],
                        usePromotionTimestamp: false,
                        useWorkspaceInPromotion: false,
                        verbose: false
                    )
                ]
       )
       echo '结束 自动部署上传到私服中的所有镜像到docker...'
    }

    echo '完成执行自动化...'
}